main: ${project.groupId}.${project.name}
name: ${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
authors: [Cayorion]
depend: [MassiveCore]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  massivebiomes.basecommand: {description: use MassiveBiomes, default: false}
  massivebiomes.here: {description: check in what biome you stand, default: false}
  massivebiomes.list: {description: list all available biomes, default: false}
  massivebiomes.pos: {description: manage positions, default: false}
  massivebiomes.pos.here: {description: set a position to where you stand, default: false}
  massivebiomes.pos.coord: {description: set a position to a coord, default: false}
  massivebiomes.convert: {description: convert from all or a specific biome to a specific biome, default: false}
  massivebiomes.config: {description: edit configuration, default: false}
  massivebiomes.version: {description: show plugin version, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  massivebiomes.*:
    default: false
    children:
      massivebiomes.basecommand: true
      massivebiomes.here: true
      massivebiomes.list: true
      massivebiomes.pos: true
      massivebiomes.pos.here: true
      massivebiomes.pos.coord: true
      massivebiomes.convert: true
      massivebiomes.config: true
      massivebiomes.version: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  massivebiomes.kit.op:
    default: op
    children:
      massivebiomes.*: true
  massivebiomes.kit.rank3:
    default: false
    children:
      massivebiomes.kit.rank2: true
      massivebiomes.pos: true
      massivebiomes.pos.here: true
      massivebiomes.pos.coord: true
      massivebiomes.convert: true
      massivebiomes.config: true
  massivebiomes.kit.rank2:
    default: false
    children:
      massivebiomes.kit.rank1: true
  massivebiomes.kit.rank1:
    default: false
    children:
      massivebiomes.kit.rank0: true
  massivebiomes.kit.rank0:
    default: false
    children:
      massivebiomes.basecommand: true
      massivebiomes.here: true
      massivebiomes.list: true
      massivebiomes.version: true
  massivebiomes.kit.default:
    default: true
    children:
      massivebiomes.kit.rank0: true
